### ISSUE TITLE
Plans for Ruby 3.0 compatibility for `crud-muffins-rails`?

### ISSUE THREAD

**Issue by anaulin** [AndrewSouthpaw/crud-muffins#10]
I'm in the process of upgrading the TransparentClassroom codebase to Ruby 3.0, and this gem, which TC still depends on, is not Ruby 3.0 compatible.

The main issue I'm running into, so far, is that the Adapter methods in https://github.com/AndrewSouthpaw/crud-muffins/blob/master/crud-muffins-rails/lib/crud-muffins-rails.rb are not delegating kwargs explicitly, in the Ruby 3.0 preferred way.

For example,
```ruby
def self.find_or_create_by(where, within: model_class)
  new(within.find_or_create_by(where))
end
```
needs to become:
```ruby
def self.find_or_create_by(*where, within: model_class, **kwhere)
  new(within.find_or_create_by(*where, **kwhere))
end
```

@AndrewSouthpaw are there any plans to update this gem for Ruby 3.0 compatibility?

**Comment by AndrewSouthpaw** [comment]
Hi there, sorry I didn't see this message. I don't have plans to upgrade to Ruby 3.0. Feel free to fork or submit a PR and I can merge it in.

**Comment by anaulin** [comment]
Hey Andrew, no worries! We figured this out for the Ruby 3 upgrade, then ended up having to fork it for the Rails 7 upgrade, so we're all set. 😺
